theme: jekyll-theme-slate
url: https://docs.devsoap.com
baseurl:
name: Devsoap Docs
title: Devsoap Docs
description: Developer documentation for Devsoap products
collections_dir: docs
collections:
  vaadin_flow_gradle_plugin:
    output: true
    title: DS Vaadin Flow Gradle Plugin
    parent: main
  vaadin_flow_gradle_plugin_groovy:
    output: true
    title: Groovy
    parent: vaadin_flow_gradle_plugin