theme: jekyll-theme-slate
url: https://docs.devsoap.com
baseurl:
name: Devsoap Docs
title: Devsoap Docs
description: Developer documentation for Devsoap products
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections_dir: docs
collections:
  vaadin_flow_gradle_plugin:
    output: true
    title: DS Vaadin Flow Gradle Plugin
    parent: main
  vaadin_flow_gradle_plugin_dependency_management:
    output: true
    title: Dependency Management
    parent: vaadin_flow_gradle_plugin
    priority: 1  
  vaadin_flow_gradle_plugin_java:
    output: true
    title: Java
    parent: vaadin_flow_gradle_plugin
    priority: 2
  vaadin_flow_gradle_plugin_groovy:
    output: true
    title: Groovy
    parent: vaadin_flow_gradle_plugin
    priority: 3
  vaadin_flow_gradle_plugin_javascript:
    output: true
    title: Javascript and Web Components
    parent: vaadin_flow_gradle_plugin
    priority: 4
  vaadin_flow_gradle_plugin_themes:
    output: true
    title: Themes and styles
    parent: vaadin_flow_gradle_plugin
    priority: 5
