theme: jekyll-theme-slate
url: https://docs.devsoap.com
baseurl:
name: Devsoap Docs
title: Devsoap Docs
description: Developer documentation for Devsoap products
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections_dir: docs
collections:
  vaadin_flow_gradle_plugin:
    output: true
    title: DS Vaadin Flow Gradle Plugin
    description: A Gradle plugin for developing Vaadin 10+ web applications.
    parent: main
    logo: https://devsoap.com/assets/graphics/pro-tool-logo.png
    sponsor_link: https://devsoap.com/store/?product=gradle-vaadin-flow
    product: gradle-vaadin-flow
  vaadin_flow_gradle_plugin_dependency_management:
    output: true
    title: Dependency Management
    parent: vaadin_flow_gradle_plugin
    priority: 1  
    product: gradle-vaadin-flow
  vaadin_flow_gradle_plugin_tasks:
    output: true
    title: Plugin tasks
    parent: vaadin_flow_gradle_plugin
    priority: 2
    product: gradle-vaadin-flow
  vaadin_flow_gradle_plugin_javascript:
    output: true
    title: Javascript and Web Components
    parent: vaadin_flow_gradle_plugin
    priority: 3
    product: gradle-vaadin-flow
  vaadin_flow_gradle_plugin_themes:
    output: true
    title: Themes and styles
    parent: vaadin_flow_gradle_plugin
    priority: 4
    product: gradle-vaadin-flow
  vaadin_flow_gradle_plugin_plugins:
    output: true
    title: 3rd party plugin support
    parent: vaadin_flow_gradle_plugin
    priority: 5
    gretty_version: 2.3.1
    product: gradle-vaadin-flow
  vaadin_flow_gradle_plugin_advanced:
    output: true
    title: Advanced topics
    parent: vaadin_flow_gradle_plugin
    priority: 6
    product: gradle-vaadin-flow
  vaadin_flow_gradle_plugin_api:
    output: true
    title: Source Documentation
    parent: vaadin_flow_gradle_plugin
    priority: 7
    comments: false  
    product: gradle-vaadin-flow
  fn_gradle_plugin:
    output: true
    title: DS FN Gradle Plugin
    description: A Gradle plugin for developing Oracle FN functions
    parent: main
    logo: https://devsoap.com/assets/graphics/pro-tool-logo.png
    sponsor_link: https://devsoap.com/store/?product=gradle-fn-plugin
  fn_gradle_plugin_tasks:
    output: true
    title: Tasks
    parent: fn_gradle_plugin
    priority: 1
  fn_gradle_plugin_multimodule:
    output: true
    title: Multi-module applications
    parent: fn_gradle_plugin  
    priority: 2
  fn_gradle_plugin_api:
    output: true
    title: Source Documentation
    parent: fn_gradle_plugin
    priority: 3
    comments: false

defaults:
  - scope:
      path: ""
      type_: "pages"
    values:
      layout: "default"
      comments: true
      priority: 100
      pro: false
      compatibility_mode: false
      version:
