#!/bin/bash

if git rev-parse --verify HEAD >/dev/null 2>&1 ; then
   against=HEAD
else
   # Initial commit: diff against an empty tree object
   against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

staged_files=`git diff-index --name-status --cached $against      | # Find all staged files
                egrep -i '^(A|M).*\.(md)$' 		          | # Only process jekyll files
                sed -e 's/^[AM][[:space:]]*//'                    | # Remove leading git info
                sort                                              | # Remove duplicates
                uniq`


partially_staged_files=`git status --porcelain --untracked-files=no | # Find all staged files
                        egrep -i '^(A|M)M '                         | # Filter only partially staged files
                        sed -e 's/^[AM]M[[:space:]]*//'             | # Remove leading git info
                        sort                                        | # Remove duplicates
                        uniq`

# Merge staged files and partially staged files
staged_and_partially_staged_files=${staged_files}$'\n'${partially_staged_files}

# Remove all files that are staged *AND* partially staged
# Thus we get only the fully staged files
fully_staged_files=`echo "$staged_and_partially_staged_files" | sort | uniq -u`

for FILE in $fully_staged_files ; do
    # substitute every jekyll modified timestamp with current timestamp
    sed -i "1,10s/modified:.*/modified: \'$(date +'%Y-%m-%d %H:%M:%S %z')\'/" "$FILE"
    git add $FILE
done

